image: python:3.11

stages:
- before_script
- linting

before_script:
    - python -m pip install --upgrade pip
    - pip install black
    - pip install flake8
    - pip install flake8-quotes
    - pip install pep8-naming
    - pip install flake8-import-order

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
    - flake8 --verbose --inline-quotes '"' --import-order-style pep8 lyceum

black:
    stage: linting
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
    - black --check --line-length 79 --verbose -- lyceum
