image: python:3.11

stages:
- before_script
- linting
- tests

before_script:
    - python3 -m pip install --upgrade pip
    - python3 -m venv venv
    - source venv/bin/activate
    - pip3 install -r requirements/test.txt

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
    - flake8 --exclude venv --verbose --inline-quotes '"' --import-order-style pep8 lyceum

black:
    stage: linting
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
    - black --exclude venv --check --line-length 79 --verbose -- lyceum

django_tests:
    stage: tests
    script:
    - python3 manage.py test
