stages:
- before_script
- linting

before_script:
    - python -m pip install --upgrade pip
    - python -m venv venv
    - source venv/bin/activate
    - pip install -r requirements.txt
    - pip install flake8

flake8:
stage: linting
image: registry.gitlab.com/pipeline-components/flake8:latest
script:
- flake8 --verbose
