image: python:3.11

stages:
- before_script
- linting

before_script:
    - python -m pip install --upgrade pip
    - pip install black
    - pip install flake8

flake8:
    stage: linting
    image: registry.gitlab.com/pipeline-components/flake8:latest
    script:
    - flake8 --verbose lyceum

black:
    stage: linting
    image: registry.gitlab.com/pipeline-components/black:latest
    script:
    - black --check --verbose -- lyceum
