[tool.flake8]
exclude = 'venv'
inline-quotes = '"'
import-order-style = 'google'
application-import-names = ['about', 'catalog', 'homepage']
count = true

[tool.black]
line-length = 79
exclude = 'venv'
