# Generated by Django 4.2.1 on 2024-02-23 19:50

import catalog.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="category",
            options={
                "verbose_name": "категория",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="item",
            options={"verbose_name": "товар", "verbose_name_plural": "товары"},
        ),
        migrations.AlterModelOptions(
            name="tag",
            options={"verbose_name": "тег", "verbose_name_plural": "теги"},
        ),
        migrations.AlterField(
            model_name="category",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="name",
            field=models.TextField(
                help_text="Максимум 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="слаг"
            ),
        ),
        migrations.AlterField(
            model_name="category",
            name="weight",
            field=models.PositiveSmallIntegerField(
                default=100,
                help_text="Вес должен быть больше нуля и меньше 32767",
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(32767),
                ],
                verbose_name="вес",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="name",
            field=models.TextField(
                help_text="Максимум 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text='Описание должно содержать слова "роскошно" или "превосходно"',
                validators=[catalog.models.item_text_validator],
                verbose_name="текст",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="is_published",
            field=models.BooleanField(
                default=True, verbose_name="опубликовано"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="name",
            field=models.TextField(
                help_text="Максимум 150 символов",
                max_length=150,
                unique=True,
                verbose_name="название",
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="слаг"
            ),
        ),
    ]
