# Generated by Django 4.2.1 on 2024-02-27 14:50

import catalog.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_category_options_alter_item_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=models.TextField(
                help_text='Описание должно содержать слова "роскошно" или "превосходно"',
                validators=[
                    catalog.validators.ValidateMustContain(
                        "роскошно", "превосходно"
                    )
                ],
                verbose_name="текст",
            ),
        ),
    ]
