# Generated by Django 4.2.1 on 2024-02-29 20:12

from django.db import migrations, models
import django.db.models.deletion

__all__ = ["Migration"]


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0002_alter_item_field"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="main_image",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="item_main",
                to="catalog.image",
                verbose_name="главное изображение",
            ),
        ),
    ]
