# Generated by Django 4.2.1 on 2024-02-29 20:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0003_alter_item_field"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="main_image",
            new_name="MainImage",
        ),
    ]
