# Generated by Django 4.2.1 on 2024-03-07 08:12

import catalog.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_remove_item_mainimage_alter_image_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="category",
            field=models.ForeignKey(
                default=catalog.models.Category.get_default_pk,
                help_text="Выберите категорию",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="items",
                related_query_name="item",
                to="catalog.category",
                verbose_name="категории",
            ),
        ),
    ]
