# Generated by Django 4.2.1 on 2024-02-23 15:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_alter_item_text"),
    ]

    operations = [
        migrations.AlterField(
            model_name="category",
            name="slug",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="Слаг"
            ),
        ),
        migrations.AlterField(
            model_name="tag",
            name="slug",
            field=models.SlugField(
                max_length=200, unique=True, verbose_name="Слаг"
            ),
        ),
    ]
