# Generated by Django 4.2.1 on 2024-03-01 11:11

import catalog.validators
from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_rename_item_main_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=django_ckeditor_5.fields.CKEditor5Field(
                help_text='Описание должно содержать слова "роскошно" или "превосходно"',
                validators=[
                    catalog.validators.ValidateMustContain(
                        "роскошно", "превосходно"
                    )
                ],
                verbose_name="текст",
            ),
        ),
    ]
