# Generated by Django 4.2.1 on 2024-02-29 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0001_squashed_0007_alter_category_name_alter_image_image_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                default="catalog/default.jpeg",
                upload_to="catalog/",
                verbose_name="изображение",
            ),
        ),
    ]
