# Generated by Django 4.2.1 on 2024-02-29 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0008_alter_image_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image",
            field=models.ImageField(
                upload_to="catalog/", verbose_name="изображение"
            ),
        ),
    ]
