# Generated by Django 4.2.1 on 2024-02-29 20:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0013_rename_main_image_item_mainimage"),
    ]

    operations = [
        migrations.RenameField(
            model_name="item",
            old_name="mainImage",
            new_name="MainImage",
        ),
    ]
