# Generated by Django 4.2.1 on 2024-03-01 10:17

import catalog.validators
import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0014_rename_mainimage_item_mainimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="item",
            name="text",
            field=ckeditor_uploader.fields.RichTextUploadingField(
                help_text='Описание должно содержать слова "роскошно" или "превосходно"',
                validators=[
                    catalog.validators.ValidateMustContain(
                        "роскошно", "превосходно"
                    )
                ],
                verbose_name="текст",
            ),
        ),
    ]
